services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - ./mysql_db_data:/var/lib/mysql

volumes:
  mysql_db_data: